"""
Module for converting DICOM images to NIfTI format. Provides a command-line interface for conversion.
"""
from typing import Optional
import SimpleITK as sitk
import argparse

class DicomToNifti:
    def convert(self, dicom_folder_path: str, nifti_file_path: Optional[str]) -> str:
        """
        Converts a DICOM folder into a NIfTI file.

        This method reads a series of DICOM images from the specified folder using SimpleITK,
        creates an image volume, and writes it out as a NIfTI file. If nifti_file_path is not provided,
        a default filename is generated by appending ".nii" to the dicom_folder_path.

        Args:
            dicom_folder_path (str): The path to the folder containing DICOM files.
            nifti_file_path (Optional[str]): The path to save the resultant NIfTI file. If None, a default
                path is generated.

        Returns:
            str: The path to the saved NIfTI file.
        """
        reader = sitk.ImageSeriesReader()
        dicom_names = reader.GetGDCMSeriesFileNames(dicom_folder_path)
        reader.SetFileNames(dicom_names)
        image = reader.Execute()

        if nifti_file_path is None:
            nifti_file_path = dicom_folder_path + ".nii"

        sitk.WriteImage(image, nifti_file_path)

        return nifti_file_path

def main():
    parser = argparse.ArgumentParser(description="Convert a DICOM folder to a NIfTI file.")
    parser.add_argument("dicom_folder_path", type=str, help="Path to the DICOM folder.")
    parser.add_argument("--nifti_file_path", type=str, help="Path to save the NIfTI file.", default=None)
    args = parser.parse_args()

    converter = DicomToNifti()
    try:
        nifti_file_path = converter.convert(args.dicom_folder_path, args.nifti_file_path)
        print(f"NIfTI file saved to: {nifti_file_path}")
    except Exception as e:
        raise RuntimeError(f"Failed to convert DICOM to NIfTI: {e}")

if __name__ == "__main__":
    main()
